# on:
#   push:
#     branches: '*'

# name: Precompile Binaries

# jobs:
#   Precompile:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       fail-fast: false
#       matrix:
#         os:
#           - ubuntu-20.04
#           - macOS-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions-rs/toolchain@v1
#         with:
#           profile: minimal
#           toolchain: stable
#           override: true
#       - name: Configure Cargo.toml optimizations
#         run: |
#           mkdir -p .cargo
#           echo "[profile.release]" >> .cargo/config.toml
#           echo "opt-level = 'z'" >> .cargo/config.toml
#           echo "lto = true" >> .cargo/config.toml
#           echo "codegen-units = 1" >> .cargo/config.toml
#           echo "panic = 'abort'" >> .cargo/config.toml
#       - uses: dart-lang/setup-dart@v1
#       - uses: subosito/flutter-action@v2
#         with:
#           channel: 'stable'
#       - name: Set up Android SDK
#         if: (matrix.os == 'ubuntu-20.04')
#         uses: android-actions/setup-android@v2 
#       - name: Install Specific NDK
#         if: (matrix.os == 'ubuntu-20.04')
#         run: sdkmanager --install "ndk;24.0.8215888"  
#       - name: Precompile (with iOS)
#         if: (matrix.os == 'macOS-latest')
#         run: dart run build_tool precompile-binaries -v --manifest-dir=../../rust --repository=LtbLightning/bdk-flutter
#         working-directory: cargokit/build_tool
#         env:
#           GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
#           PRIVATE_KEY: ${{ secrets.RELEASE_PRIVATE_KEY }}
#       - name: Precompile (with Android)
#         if: (matrix.os == 'ubuntu-20.04')
#         run: dart run build_tool precompile-binaries -v --manifest-dir=../../rust --repository=LtbLightning/bdk-flutter --android-sdk-location=/usr/local/lib/android/sdk --android-ndk-version=24.0.8215888 --android-min-sdk-version=23
#         working-directory: cargokit/build_tool
#         env:
#           GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
#           PRIVATE_KEY: ${{ secrets.CARGOKIT_PRIVATE_KEY }}


on:
  push:
    branches: [ master ]

name: Precompile Binaries

jobs:
  Precompile:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - name: Install GTK
        if: (matrix.os == 'ubuntu-latest')
        run: sudo apt-get update && sudo apt-get install libgtk-3-dev
      - name: Precompile
        if: (matrix.os == 'macOS-latest') || (matrix.os == 'windows-latest')
        run: dart run build_tool precompile-binaries -v --manifest-dir=../../rust --repository=ethicnology/rust-bip85
        working-directory: bindings/dart-bip85/cargokit/build_tool
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          PRIVATE_KEY: ${{ secrets.RELEASE_PRIVATE_KEY }}
      - name: Precompile (with Android)
        if: (matrix.os == 'ubuntu-latest')
        run: dart run build_tool precompile-binaries -v --manifest-dir=../../rust --repository=ethicnology/rust-bip85 --android-sdk-location=/usr/local/lib/android/sdk --android-ndk-version=24.0.8215888 --android-min-sdk-version=23
        working-directory: bindings/dart-bip85/cargokit/build_tool
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          PRIVATE_KEY: ${{ secrets.RELEASE_PRIVATE_KEY }}